### ISSUE TITLE
Tetromino Spriting To-Do

### ISSUE THREAD

**Issue by Gamedev-Eira** [Gamedev-Eira/Nottris#1]
- [x] Create base tetromino sprite
- [x] Create general colour-palette
- [x] Create Trichomancy-Friendly colour-palette
- [x] Create Dichromatic-Friendly colour-palette
- [x] Create Monochromatic-Friendly colour-palette
